### ISSUE TITLE
Video0

### ISSUE THREAD

**Issue by shahbazaly** [InES-HPMM/FPD-LinkIII_ds90ub95x#4]
Dear Sir, 
I have got the deserializer and serializer made from a manufacturer in Germany. I am currently trying to get images through these on the the raspberrypi4. I can not seem to get the video0. I do get it when I connect the camera directly to the raspberrypi4. I have used the modprobe command aswell but it does not do anything. In the raspberrypi configuration I have not switched on any other interface. The leds don't blink either. I cant seem to understand the pass and lock leds functionalities.
Do you think there could be a problem in the hardware that I got from the manufacturer? some soldering issue? I really need to get this working. Need your assistance. Thank you. 
I have attached error images and my setup. 

![20210107_132030](https://user-images.githubusercontent.com/73706851/104016183-126d9000-51b6-11eb-934a-60f6f17460ba.jpg)
![20210108_130747](https://user-images.githubusercontent.com/73706851/104016297-59f41c00-51b6-11eb-86b8-35e1f9ed94f2.jpg)

**Comment by dariis** [comment]
On the picture of your setup the jumpers for the power supply are missing.

**Comment by hubpZHAW** [comment]
And it seems that you have an error in the device-tree entry for ds09ub954. Can you post you device tree entry for ds90ub954?

**Comment by shahbazaly** [comment]
Thank you for the response. I guess I am missing jumpwire. I have attached a picture can you please confirm if its the same one? Thank you. 
![Screenshot from 2021-01-08 17-17-56](https://user-images.githubusercontent.com/73706851/104038914-fd085e00-51d5-11eb-8a50-e86fa3c9cecc.png)

**Comment by shahbazaly** [comment]
I have error in the device-tree because I did not follow the steps further. I stopped after the video0 was not found. I do not have the driver installed in my linux yet. Thank you.

**Comment by dariis** [comment]
> Thank you for the response. I guess I am missing jumpwire. I have attached a picture can you please confirm if its the same one? Thank you.
> ![Screenshot from 2021-01-08 17-17-56](https://user-images.githubusercontent.com/73706851/104038914-fd085e00-51d5-11eb-8a50-e86fa3c9cecc.png)

Looks good. As long as the pitch is the same as the header you should be good.
